In [1]:
import numpy as np 

In [3]:
matriza= np.array([[-6, 3],[4, 5]])

vals, vecs = np.linalg.eig(matriza)
print(vals)
print('\n', vecs)

[-7.  6.]

 [[-0.9486833  -0.24253563]
 [ 0.31622777 -0.9701425 ]]


In [5]:
# we have to transform eigenvalues to diagonal 
vals_diag = np.diag(vals)
print(vals_diag)

[[-7.  0.]
 [ 0.  6.]]


In [6]:
# we have to get the inverse of the eigenvectors
vecs_inverse = np.linalg.inv(vecs)
print(vecs_inverse)

[[-0.97300851  0.24325213]
 [-0.31716197 -0.95148591]]


In [8]:
# final equation
A = np.dot(np.dot(vecs, vals_diag), vecs_inverse)
A

array([[-6.,  3.],
       [ 4.,  5.]])

In [9]:
# FUCKING GOOD JOB WE MADE IT!

In [10]:
def symmetric_matrix(matriza):
    vals, vecs = np.linalg.eig(matriza)
    # we have to transform eigenvalues to diagonal 
    vals_diag = np.diag(vals)
    # we have to get the inverse of the eigenvectors
    vecs_inverse = np.linalg.inv(vecs)
    A = np.dot(np.dot(vecs, vals_diag), vecs_inverse)
    return A
    

In [13]:
matrix_a = np.array([[2, 1],[1, 2]])
matrix_b = np.array([[2, 0],[0, 2]])
matrix_c = np.array([[2, 1],[0, 2]])

a = symmetric_matrix(matrix_a)
b = symmetric_matrix(matrix_b)
c = symmetric_matrix(matrix_c)

print(a,'\n \n ', b, '\n \n ', c)

[[2. 1.]
 [1. 2.]] 
 
  [[2. 0.]
 [0. 2.]] 
 
  [[2. 0.]
 [0. 2.]]
